<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>DanfeSharp.NFSe</RootNamespace>
    <AssemblyName>DanfeSharp.NFSe</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppDesignerFolder>Properties</AppDesignerFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDFClown" Version="0.1.2" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DanfeSharp\DanfeSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\LogoNFSe.png">
      <LogicalName>DanfeSharp.NFSe.Resources.LogoNFSe.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
